services:
  neo4j:
    image: neo4j:5.15-community
    container_name: musicgraph_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/musicgraph_pass
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    volumes:
      - ./data:/data
      - ./import:/var/lib/neo4j/import
    networks:
      - music_net

networks:
  music_net:
    driver: bridge